services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://todouser:todopass@postgres:5432/tododb

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"

volumes:
  postgres_data: